services:
  - type: web
    name: umidade-br
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k gthread -w 2 -t 120 -b 0.0.0.0:$PORT app:server
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: ATTR_XLSX
        value: "arquivo_completo_brasil.xlsx"   # <- estava data/arquivo...
      # (opcional) só se você for subir um geojson na RAIZ:
      # - key: GEOJSON_PATH
      #   value: "municipios_br.geojson"
      - key: REFRESH_TOKEN
        generateValue: true
